src/Orneholm.CognitiveWorkbench.Web/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.ApplicationInsights;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Orneholm.CognitiveWorkbench.Web.Models.TextAnalytics;
using Orneholm.CognitiveWorkbench.Web.Services;

namespace Orneholm.CognitiveWorkbench.Web.Controllers
{
    public class LanguageController : Controller
    {
        private readonly ILogger<LanguageController> _logger;
        private readonly TelemetryClient _telemetryClient;

        public LanguageController(ILogger<LanguageController> logger, TelemetryClient telemetryClient)
        {
            _logger = logger;
            _telemetryClient = telemetryClient;
        }

        [HttpGet("/language/text-analytics")]
        public IActionResult TextAnalytics()
        {
            return View(TextAnalyticsViewModel.NotAnalyzed());
        }

        [HttpPost("/language/text-analytics")]
        public async Task<ActionResult<TextAnalyticsViewModel>> TextAnalytics([FromForm]TextAnalyticsAnalyzeRequest request)
        {
            if (string.IsNullOrWhiteSpace(request.TextAnalyticsSubscriptionKey))
            {
                throw new ArgumentException("Missing or invalid TextAnalyticsSubscriptionKey", nameof(request.TextAnalyticsSubscriptionKey));
            }

            if (string.IsNullOrWhiteSpace(request.TextAnalyticsEndpoint))
            {
                throw new ArgumentException("Missing or invalid TextAnalyticsEndpoint", nameof(request.TextAnalyticsEndpoint));
            }

            if (string.IsNullOrWhiteSpace(request.Text))
            {
                throw new ArgumentException("Missing or invalid Text", nameof(request.Text));
            }

            Track("Language_TextAnalytics");

            var textAnalyzer = new LanguageTextAnalyticsAnalyzer(request.TextAnalyticsSubscriptionKey, request.TextAnalyticsEndpoint);
            var analyzeResult = await textAnalyzer.Analyze(request.Text, request.LanguageHint);

            return View(TextAnalyticsViewModel.Analyzed(request, analyzeResult));
        }

        private void Track(string type)
        {
            _telemetryClient.TrackEvent("AnalyzeLanguage", new Dictionary<string, string>
            {
                { "cwb_type", type }
            });
        }
    }
}

src/Orneholm.CognitiveWorkbench.Web/Controllers/VisionController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.ApplicationInsights;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Orneholm.CognitiveWorkbench.Web.Models.ComputerVision;
using Orneholm.CognitiveWorkbench.Web.Models.CustomVision;
using Orneholm.CognitiveWorkbench.Web.Models.Face;
using Orneholm.CognitiveWorkbench.Web.Services;

namespace Orneholm.CognitiveWorkbench.Web.Controllers
{
    public class VisionController : Controller
    {
        private readonly ILogger<VisionController> _logger;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly TelemetryClient _telemetryClient;

        private List<string> _allowedFileContentType = new List<string> { "image/jpeg", "image/png", "image/gif", "image/bmp" };

        public VisionController(ILogger<VisionController> logger, IHttpClientFactory httpClientFactory, TelemetryClient telemetryClient)
        {
            _logger = logger;
            _httpClientFactory = httpClientFactory;
            _telemetryClient = telemetryClient;
        }

        [HttpGet("/vision/computer-vision")]
        public IActionResult ComputerVision()
        {
            return View(ComputerVisionViewModel.NotAnalyzed());
        }

        [HttpPost("/vision/computer-vision")]
        public async Task<ActionResult<ComputerVisionViewModel>> ComputerVision([FromForm]ComputerVisionAnalyzeRequest request)
        {
            var errorContent = "";
            if (string.IsNullOrWhiteSpace(request.ComputerVisionSubscriptionKey))
            {
                errorContent += $"Missing or invalid Computer Vision Subscription Key (see 'Azure Settings' tab){Environment.NewLine}";
            }

            if (string.IsNullOrWhiteSpace(request.ComputerVisionEndpoint))
            {
                errorContent += $"Missing or invalid Computer Vision Endpoint (see 'Azure Settings' tab){Environment.NewLine}";
            }

            if (string.IsNullOrWhiteSpace(request.ImageUrl) && (request.File == null || !_allowedFileContentType.Contains(request.File.ContentType)))
            {
                errorContent += $"Missing or invalid ImageUrl / no file provided";
            }

            if (!string.IsNullOrWhiteSpace(errorContent))
            {
                return View(ComputerVisionViewModel.Analyzed(request, 
                    new ComputerVisionAnalyzeResponse
                    {
                        OtherErrorMessage = "Request not processed due to the following error(s):",
                        OtherErrorContent = errorContent
                    }));
            }

            Track("Vision_ComputerVision");

            var imageAnalyzer = new ImageComputerVisionAnalyzer(request.ComputerVisionSubscriptionKey, request.ComputerVisionEndpoint, _httpClientFactory);
            var analyzeResult = await imageAnalyzer.AnalyzeAsync(request.ImageUrl, request.File, request.ImageAnalysisLanguage, request.ImageOcrLanguage, request.ImageReadLanguage);

            return View(ComputerVisionViewModel.Analyzed(request, analyzeResult));
        }

        [HttpGet("/vision/custom-vision")]
        public IActionResult CustomVision()
        {
            return View(CustomVisionViewModel.NotAnalyzed());
        }

        [HttpPost("/vision/custom-vision")]
        public async Task<ActionResult<CustomVisionViewModel>> CustomVision([FromForm]CustomVisionRequest request)
        {
            var errorContent = "";
            if (string.IsNullOrWhiteSpace(request.CustomVisionPredictionKey))
            {
                errorContent += $"Missing or invalid Custom Vision Prediction Key (see 'Azure Settings' tab){Environment.NewLine}";
            }

            if (string.IsNullOrWhiteSpace(request.CustomVisionEndpoint))
            {
                errorContent += $"Missing or invalid Custom Vision Prediction Endpoint (see 'Azure Settings' tab){Environment.NewLine}";
            }

            if (string.IsNullOrWhiteSpace(request.ImageUrl) && (request.File == null || !_allowedFileContentType.Contains(request.File.ContentType)))
            {
                errorContent += $"Missing or invalid ImageUrl / no file provided{Environment.NewLine}";
            }

            if (request.ProjectId == null || Guid.Empty.Equals(request.ProjectId))
            {
                errorContent += $"Missing or invalid Project Id{Environment.NewLine}";
            }

            if (string.IsNullOrWhiteSpace(request.IterationPublishedName))
            {
                errorContent += $"Missing or invalid Iteration Published Name{Environment.NewLine}";
            }

            if (!string.IsNullOrWhiteSpace(errorContent))
            {
                return View(CustomVisionViewModel.Analyzed(request, 
                    new CustomVisionResponse
                    {
                        OtherErrorMessage = "Request not processed due to the following error(s):",
                        OtherErrorContent = errorContent
                    }));
            }

            Track("Vision_CustomVision");

            var imageAnalyzer = new ImageCustomVisionAnalyzer(request.CustomVisionPredictionKey, request.CustomVisionEndpoint, _httpClientFactory);
            var analyzeResult = await imageAnalyzer.AnalyzeAsync(request.ImageUrl, request.File, request.ProjectId, request.IterationPublishedName, request.ProjectType);

            return View(CustomVisionViewModel.Analyzed(request, analyzeResult));
        }

        [HttpGet("/vision/face")]
        public IActionResult Face()
        {
            return View(FaceViewModel.NotAnalyzed());
        }

        [HttpPost("/vision/face")]
        public async Task<ActionResult<FaceViewModel>> Face([FromForm]FaceAnalyzeRequest request)
        {
            var errorContent = "";
            if (string.IsNullOrWhiteSpace(request.FaceSubscriptionKey))
            {
                errorContent += $"Missing or invalid Face Subscription Key (see 'Azure Settings' tab){Environment.NewLine}";
            }

            if (string.IsNullOrWhiteSpace(request.FaceEndpoint))
            {
                errorContent += $"Missing or invalid Face Endpoint (see 'Azure Settings' tab){Environment.NewLine}";
            }

            if (string.IsNullOrWhiteSpace(request.ImageUrl) && (request.File == null || !_allowedFileContentType.Contains(request.File.ContentType)))
            {
                errorContent += $"Missing or invalid ImageUrl / no file provided{Environment.NewLine}";
            }

            if (request.EnableIdentification && string.IsNullOrWhiteSpace(request.IdentificationGroupId))
            {
                errorContent += $"Missing or invalid Identification Group Id{Environment.NewLine}";
            }

            if (!string.IsNullOrWhiteSpace(errorContent))
            {
                return View(FaceViewModel.Analyzed(request, 
                    new FaceAnalyzeResponse
                    {
                        OtherErrorMessage = "Request not processed due to the following error(s):",
                        OtherErrorContent = errorContent
                    }));
            }

            Track("Vision_Face");

            var imageAnalyzer = new ImageFaceAnalyzer(request.FaceSubscriptionKey, request.FaceEndpoint, _httpClientFactory);
            var analyzeResult = await imageAnalyzer.AnalyzeAsync(request.ImageUrl, request.File,request.DetectionModel, request.EnableIdentification, request.RecognitionModel, request.IdentificationGroupType, request.IdentificationGroupId);

            return View(FaceViewModel.Analyzed(request, analyzeResult));
        }

        private void Track(string type)
        {
            _telemetryClient.TrackEvent("AnalyzeImage", new Dictionary<string, string>()
            {
                { "cwb_type", type }
            });
        }
    }
}

src/Orneholm.CognitiveWorkbench.Web/Views/Shared/_ColorSampleBlock.cshtml
@model string

<div class="cwb-color-sample-block" style="background-color: #@(Model); background-color: @(Model)" title="@Model"></div>

src/Orneholm.CognitiveWorkbench.Web/Views/Shared/_DetectResult.cshtml
@using Orneholm.CognitiveWorkbench.Web.Extensions
@model FaceAnalyzeResponse

<div class="mb-5">
    <h4>Faces</h4>

    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Age</th>
                <th>Smile</th>
                <th>Rectangle</th>
            </tr>
        </thead>
        <tbody class="cwb-image-boxes-table" data-cwb-for=".cwb-image-boxes-faces-full">
            @foreach (var face in Model.FaceResult)
            {
                <tr>
                    <th>@face.FaceAttributes?.Age</th>
                    <th>@face.FaceAttributes?.Smile</th>
                    <th>@face.FaceRectangle.ToDescription()</th>
                </tr>
            }
        </tbody>
    </table>

    @if (!Model.FaceResult.Any())
    {
        <p class="p-2">
            No faces available.
        </p>
    }
</div>

<div class="mt-5">
    <h4>Metadata</h4>

    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Width (px)</th>
                <td>@Model.ImageInfo.Width</td>
            </tr>
            <tr>
                <th>Height (px)</th>
                <td>@Model.ImageInfo.Height</td>
            </tr>
        </tbody>
    </table>
</div>

src/Orneholm.CognitiveWorkbench.Web/Views/Shared/_Json.cshtml
@model object
@inject IJsonHelper JsonHelper

<pre class="prettyprint lang-json">@JsonHelper.Serialize(Model)</pre>

src/Orneholm.CognitiveWorkbench.Web/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Options
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@inject IOptions<GoogleAnalyticsOptions> GoogleAnalyticsOptions
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <base href="/" />

    <!-- CREDITS -->
    <!--

    This site is created and maintained by Peter Örneholm.

    https://twitter.com/PeterOrneholm
    https://peter.orneholm.com/

    Source available at GitHub:
    https://github.com/PeterOrneholm/cognitive-workbench

    -->
    <!-- Meta -->
    <title>Cognitive Workbench - Interactive workbench to try out Azure Cognitive Services</title>
    <meta name="author" content="Peter Örneholm (@@PeterOrneholm)">
    <meta name="description" content="Interactive workbench to try out Azure Cognitive Services.">

    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="/images/icons/cognitiveworkbench-180x180.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/icons/cognitiveworkbench-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/icons/cognitiveworkbench-16x16.png">

    <link rel="shortcut icon" href="/favicon.ico">

    <!-- Webapp -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="manifest" href="/manifest.webmanifest">

    <!-- Styles -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.12.1/css/all.css" integrity="sha384-TxKWSXbsweFt0o2WqfkfJRRNVaPdzXJ/YLqgStggBVRREXkwU7OKz+xXtqOU4u8+" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.10.1/css/mdb.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    @if (!string.IsNullOrWhiteSpace(GoogleAnalyticsOptions.Value.GoogleAnalyticsKey))
    {
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=@(GoogleAnalyticsOptions.Value.GoogleAnalyticsKey)"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '@GoogleAnalyticsOptions.Value.GoogleAnalyticsKey');
        </script>
    }

    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-white cwb-navbar fixed-top">
    <div class="container">
        <a class="navbar-brand cwb-navbar-brand" href="/"><i class="fas fa-brain"></i> Cognitive Workbench</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Vision" asp-action="ComputerVision">Computer Vision</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Vision" asp-action="Face">Face</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Vision" asp-action="CustomVision">Custom Vision</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Language" asp-action="TextAnalytics">Text Analytics</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="bg-light cwb-main-content-wrapper">
    @RenderBody()
</div>

<footer class="cwb-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h4>About</h4>
                <p>
                    This site provides an interactive workbench to try out <a href="https://www.microsoft.com/cognitive-services">Azure Cognitive Services</a>.
                </p>
                <p>
                    The <a href="https://github.com/PeterOrneholm/cognitive-workbench">Sourcecode is available at GitHub</a> and <a href="https://hub.docker.com/r/peterorneholm/orneholmcognitiveworkbenchweb">Docker image available at Dockerhub</a>.
                </p>
            </div>

            <div class="col-sm-4">
                <h4>Privacy</h4>
                <p>
                    This site don't store any of the data (settings, pictures or URL:s) you enter in this application on the server. To see how the site performs, we do keep anonymized statistics of usage.
                </p>
                <p>
                    The application will remember your settings locally (in local storage) for easier usage.
                </p>
            </div>

            <div class="col-sm-4">
                <h4>Author</h4>
                <p>
                    Developed by <a href="https://twitter.com/PeterOrneholm" target="_blank">@@PeterOrneholm</a> at <a href="https://www.activesolution.se/">Active Solution</a> as a demo for the session <a href="http://bit.ly/peterorneholm-democratizing-ai">Democratizing AI with Azure Cognitive Services</a>.
                </p>
                <p>
                    This site is part of a set of AI Experiments:

                    <ul class="list-unstyled mt-1">
                        <li><a href="https://birdornot.net/">BirdOrNot.net</a></li>
                        <li><a href="https://cogbox.net/">CogBox.net</a></li>
                        <li><a href="https://radiotext.net/">RadioText.net</a></li>
                    </ul>
                </p>
                <h5>Contributors</h5>
                <p>
                    Thanks to <a href="https://twitter.com/NicoRobPro" target="_blank">@@NicoRobPro</a> for some great additions to this site.
                </p>
            </div>
        </div>
        <p class="cwb-footer-sitename">
            Cognitive Workbench
        </p>
    </div>
</footer>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

@RenderSection("Scripts", required: false)
</body>
</html>